---
version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  simple_agent:
    format: "%(asctime)s - %(name)s - %(levelname)s\n%(message)s"
handlers:
  agent_console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple_agent
    stream: ext://sys.stdout
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class : logging.handlers.RotatingFileHandler
    formatter: simple
    filename: mimic-game.log
    maxBytes: 1024
    backupCount: 3
# Set the log levels according to this chart
# https://docs.python.org/3/library/logging.html#logging-levels
loggers:
  agent:
    level: ERROR
    handlers:
      - agent_console
      # - file
    propagate: no
  game:
    level: INFO
    handlers:
      - console
      # - file
    propagate: no
root:
  level: DEBUG
  handlers: [console]
